#!/usr/bin/env bash

# Bring system up-to-date and install essential packages
#softwareupdate -ia
xcode-select --install
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Clone DOTFILES repository and override existing profile
sh -c "brew install yadm"
sh -c "yadm clone https://github.com/tornupnegatives/dotfiles.git"
sh -c "yadm checkout -- ~/.profile"
ln -s ~/.profile ~/.zprofile

# Set up ZSH directories
if [ ! -d "$HOME/.config/zsh" ]; then
    mkdir -p "$HOME/.config/zsh"
fi

# Install oh-my-zsh
wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
chmod +x install.sh

ZDOTDIR="$HOME/.config/zsh" XDG_DATA_HOME="$HOME/.local/share" \
    sh -c "~/install.sh"

# Cleanup
rm -f ~/.bash* ~/install.sh ~/.wget* ~/.zsh_history
