#!/usr/bin/env bash

# Be sure to run as target user!
# $ chmod +x bootstrap-ubuntu
# $ sudo -u $(whoami) ./bootstrap-ubuntu

# Bring system up-to-date and install recommended drivers
sudo apt update && sudo apt upgrade -y && sudo ubuntu-drivers install

# Dump original APT state for reference
sudo apt-mark showmanual >> ~/.apt-init.txt

# Install GNOME Software Center and Flatpak
sudo apt install -y gnome-software flatpak gnome-software-plugin-flatpak gnome-software-plugin-snap
flatpak remote-add flathub https://dl.flathub.org/repo/flathub.flatpakrepo

# Install essential packages
sudo apt install -y nala
sudo sh -c "nala install -y build-essential git vim yadm zsh"

# Clone DOTFILES repository and override existing profile
sh -c "yadm clone https://github.com/tornupnegatives/dotfiles.git"
sh -c "yadm checkout -- ~/.profile"
ln -s ~/.profile ~/.zprofile

# Set up ZSH directories
if [ ! -d "$HOME/.config/zsh" ]; then
    mkdir -p "$HOME/.config/zsh"
fi

# Install oh-my-zsh
wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
chmod +x install.sh

ZDOTDIR="$HOME/.config/zsh" XDG_DATA_HOME="$HOME/.local/share" \
    sh -c "~/install.sh"

# Cleanup
rm -f ~/.bash* ~/install.sh ~/.wget* ~/.zsh_history
