#!/usr/bin/env bash

# Install dependencies (Linux only)
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    sudo apt update
    sudo apt upgrade -y
    sudo apt install curl build-essential vim zsh -y
fi

# Install Homebrew
if ! command -v brew > /dev/null; then
    echo "@ Homebrew not found. Installing..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    echo "@ Homebrew found. No action needed"
fi

# Install oh-my-zsh
if [ ! -d ${XDG_DATA_HOME}/oh-my-zsh ]; then
    echo "@ oh-my-zsh not found. Installing..."
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
    echo "@ oh-my-zsh found. No action needed"
fi

# Remove any residual Bash files
mkdir -p ${HOME}/DELETE_ME
for f in ${HOME}/.bash* do
  mv "$f" ${HOME}/DELETE_ME/.
done

# Symlink .profile -> .zprofile for macOS shell or Linux login shell
if [[ ! -e "${HOME}/.zprofile" ]]; then
    ln -s ${HOME}/.profile ${HOME}/.zprofile
fi

